apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: api-network-delay
  namespace: default
spec:
  action: delay
  mode: all
  duration: "1m"
  selector:
    labelSelectors:
      app: api
  direction: to
  delay:
    latency: "3000ms"
    jitter: "500ms"
